
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fnplot.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 41;
  public static final int CONCAT = 4;
  public static final int CASE = 30;
  public static final int INTEGER = 37;
  public static final int NOTEQUAL = 8;
  public static final int LPAREN = 2;
  public static final int SEMI = 23;
  public static final int MINUS = 12;
  public static final int RPAREN = 3;
  public static final int EQLTHAN = 9;
  public static final int DEFINE = 27;
  public static final int NOT = 36;
  public static final int AND = 35;
  public static final int LTHAN = 6;
  public static final int IN = 19;
  public static final int OR = 34;
  public static final int BOOL = 40;
  public static final int COMMA = 22;
  public static final int CALL = 26;
  public static final int BAND = 32;
  public static final int DIV = 14;
  public static final int BNOT = 33;
  public static final int PLUS = 11;
  public static final int ASSIGN = 16;
  public static final int EXP = 17;
  public static final int EOF = 0;
  public static final int EQUAL = 7;
  public static final int error = 1;
  public static final int MUL = 13;
  public static final int MOD = 15;
  public static final int EQGTHAN = 10;
  public static final int REAL = 39;
  public static final int GTHAN = 5;
  public static final int COLON = 24;
  public static final int BOR = 31;
  public static final int LBRACE = 20;
  public static final int ELSE = 29;
  public static final int VARIABLE = 38;
  public static final int LET = 18;
  public static final int THEN = 28;
  public static final int RBRACE = 21;
  public static final int STRING = 42;
  public static final int PROC = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "CONCAT",
  "GTHAN",
  "LTHAN",
  "EQUAL",
  "NOTEQUAL",
  "EQLTHAN",
  "EQGTHAN",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "ASSIGN",
  "EXP",
  "LET",
  "IN",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "SEMI",
  "COLON",
  "PROC",
  "CALL",
  "DEFINE",
  "THEN",
  "ELSE",
  "CASE",
  "BOR",
  "BAND",
  "BNOT",
  "OR",
  "AND",
  "NOT",
  "INTEGER",
  "VARIABLE",
  "REAL",
  "BOOL",
  "CHAR",
  "STRING"
  };
}

